- name: install php php-fpm & php-curl
  apt:
    name:
      - php
      - php-fpm
      - php-curl
    state: present
    update_cache: yes

- name: start php-fpm
  service:
    name: php8.4-fpm
    state: started
    enabled: yes

- name: Aseta Discord webhook PHP-FPM:lle
  lineinfile:
    path: "/etc/php/8.4/fpm/pool.d/www.conf"
    line: "env[DISCORD_WEBHOOK_URL] = '{{ discord_url }}'"
    insertafter: EOF
  notify: restart php8.4-fpm

- name: copy yhteydenottolomake
  copy:
    src: yhteydenotto.php
    dest: /var/www/html/yhteydenotto.php
    owner: www-data
    group: www-data
    mode: '0644'
