- name: create web root
  file:
    path: /var/www/etusivu
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: copy frontpage index.html
  copy:
    src: etusivu/index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: create erkka directory
  file:
    path: /var/www/html/erkka
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'

- name: create vili directory
  file:
    path: /var/www/html/vili
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'


- name: copy erkka_photo
  copy:
    src: erkka/erkka.jpg
    dest: /var/www/html/erkka/erkka.jpg
    owner: www-data
    group: www-data
    mode: '0644'

- name: copy vili_photo
  copy:
    src: vili/vili.png
    dest: /var/www/html/vili/vili.png
    owner: www-data
    group: www-data
    mode: '0644'

- name: copy erkka html
  file:
    src: erkka/index.html
    path: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: copy vili html
  file:
    src: vili/index.html
    path: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: copy 404 gif
  copy:
    src: 404/giphy.gif
    dest: /var/www/html/giphy.gif
    owner: www-data
    group: www-data
    mode: '0644'

- name: copy 404 html
  copy:
    src: 404/404.html
    dest: /var/www/html/404.html
    owner: www-data
    group: www-data
    mode: '0644'

