- name: create web root
  file:
    path: /var/www/etusivu
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: copy frontpage index.html
  copy:
    src: etusivu/index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: create erkka directory
  file:
    path: /var/www/html/erkka
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'

- name: create vili directory
  file:
    path: /var/www/html/vili
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'

- name: copy erkka
  copy:
    src: erkka
    dest: /var/www/html/erkka
    owner: www-data
    group: www-data
    mode: '0644'

- name: copy vili
  copy:
    src: vili
    dest: /var/www/html/vili
    owner: www-data
    group: www-data
    mode: '0644'


- name: copy 404
  copy:
    src: 404
    dest: /var/www/html
    owner: www-data
    group: www-data
    mode: '0644'

