# This is a moderated file, all changes will be overwritten

server {
    listen 80;
    server_name uncleco.com;

    root /var/www/etusivu;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
